import jsPDF from 'jspdf'

export function generatePdf(title: string, content: string) {
  const doc = new jsPDF()
  
  // Add title
  doc.setFontSize(16)
  doc.text(title, 20, 20)
  
  // Add content with word wrap
  doc.setFontSize(12)
  const splitText = doc.splitTextToSize(content, 170) // 170 is the max width
  doc.text(splitText, 20, 30)
  
  // Add footer with GTMGuy branding
  doc.setFontSize(10)
  doc.setTextColor(100, 100, 100)
  doc.text('Generated by GTMGuy.ai', 20, doc.internal.pageSize.height - 20)
  
  // Generate download
  doc.save(`GTMGuy-${title.toLowerCase().replace(/\s+/g, '-')}.pdf`)
} 